@baseURL = http://localhost:3999
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc2MDgwODAyLCJleHAiOjE3Nzg2NzI4MDJ9.IsAXM53COB-wkIPfDZkfxuswwlG-3m954sbXczj_dg4


### Login
POST {{baseURL}}/api/auth/login
Content-Type: application/json

{
    "email":"peach@gmail.com",
    "password": "123456" 
}



##################ACTIVITY
### GET act
GET {{baseURL}}/api/activity

### GET act on this acc
GET {{baseURL}}/api/activity/my-activities
Authorization: Bearer {{token}}

### GET act by cat
GET {{baseURL}}/api/activity/category/art

### POST Activity
POST {{baseURL}}/api/activity
Authorization: Bearer {{token}}

    {
        "category": "ART",
        "title": "TODLONG Workshop @Ari 🎨",
        "description": "Workshops ระบายสีน้ำแถวอารีย์ ไม่ต้องมีพื้นฐานก็มาได้นะ มาลองสร้าง Masterpiece ของตัวเองในคาเฟ่บรรยากาศ Cozy สุดๆ",
        "eventStartTime": "2026-04-21T13:00:00.000Z",
        "hostId": 5,
        "placeId": 5
    }


### GET act id
GET {{baseURL}}/api/activity/2

### GET act id
GET {{baseURL}}/api/activity/5

### DELETE act id
DELETE {{baseURL}}/api/activity/1
Authorization: Bearer {{token}}


### status act
PATCH {{baseURL}}/api/activity/status/5
Content-Type: application/json

{
    "status": "FULL"
}




##################PROFILE
### GET profile
GET {{baseURL}}/api/account/profile
Authorization: Bearer {{token}}